"""Deliverable: the submission file (1-14 Nov 2025) from the saved final model, plus the stretch goal:
calibrated prediction intervals.

Run from the repo root:  python -m src.predict
"""
from __future__ import annotations

import joblib
import numpy as np
import pandas as pd

from src import config
from src import train as T

LEVELS = {"80": (0.10, 0.90), "90": (0.05, 0.95)}
CALIB_CUTS = ["2025-10-04", "2025-10-18"]   # the two latest 14-day folds


def load_bundle():
    return joblib.load(config.MODELS / "final_model.joblib")


def predict_test(bundle, test: pd.DataFrame) -> np.ndarray:
    return np.clip(bundle["model"].predict(test[bundle["features"]]), 0, None)


def _scaled_residuals(m, cut, feats, params):
    """Train on everything before `cut`, predict the next 14 days; residuals scaled by sqrt(pred + 1) because
    count errors grow with the size of the forecast."""
    tr, va = T.split(m, cut)
    _, p, _ = T.fit_predict("lightgbm", tr, va, feats, params)
    return va.assign(pred=p, z=(va[T.TARGET] - p) / np.sqrt(p + 1))


def interval(pred, q_lo, q_hi):
    s = np.sqrt(np.asarray(pred) + 1)
    return np.clip(pred + q_lo * s, 0, None), pred + q_hi * s


def calibrate(m, feats, params):
    """Split-conformal style intervals. Honest check: quantiles taken from the 4-17 Oct fold, coverage measured
    on 18-31 Oct. Final quantiles pool both folds."""
    folds = {c: _scaled_residuals(m, c, feats, params) for c in CALIB_CUTS}
    first, last = folds[CALIB_CUTS[0]], folds[CALIB_CUTS[1]]
    rows = []
    for lvl, (a, b) in LEVELS.items():
        lo, hi = interval(last.pred, first.z.quantile(a), first.z.quantile(b))
        y = last[T.TARGET].values
        rows.append({"interval": f"{lvl}%", "target_coverage": int(lvl) / 100,
                     "coverage_18_31_oct": float(np.mean((y >= lo) & (y <= hi))),
                     "mean_width_trips": float(np.mean(hi - lo))})
    pooled = pd.concat([first.z, last.z])
    quantiles = {lvl: (float(pooled.quantile(a)), float(pooled.quantile(b))) for lvl, (a, b) in LEVELS.items()}
    return pd.DataFrame(rows), quantiles, last


def main():
    bundle = load_bundle()
    raw = pd.read_csv(config.RAW / "ride_demand_test.csv", usecols=["row_id"])
    test = T.load_master_test()
    assert test["row_id"].is_unique and set(test["row_id"]) == set(raw["row_id"])
    test = raw.merge(test, on="row_id", how="left")            # original row order

    pred = predict_test(bundle, test)
    sub = pd.DataFrame({"row_id": test["row_id"], "predicted_trips": np.round(pred, 2)})
    assert len(sub) == 4032 and sub["predicted_trips"].notna().all() and (sub["predicted_trips"] >= 0).all()
    assert (sub["row_id"].values == raw["row_id"].values).all()
    config.SUBMISSION.mkdir(exist_ok=True)
    sub.to_csv(config.SUBMISSION_FILE, index=False)
    print(f"wrote {config.SUBMISSION_FILE.relative_to(config.ROOT)}: {len(sub)} rows, "
          f"mean {sub.predicted_trips.mean():.1f}, min {sub.predicted_trips.min():.2f}, max {sub.predicted_trips.max():.1f}")

    # Stretch goal: prediction intervals
    m = T.load_master_train()
    cov, q, last = calibrate(m, bundle["features"], bundle["params"])
    out = test[["row_id", "zone", "pickup_hour"]].assign(predicted_trips=sub["predicted_trips"])
    for lvl, (a, b) in q.items():
        lo, hi = interval(pred, a, b)
        out[f"lower_{lvl}"], out[f"upper_{lvl}"] = np.round(lo, 1), np.round(hi, 1)
    out["drivers_needed"] = np.ceil(out.predicted_trips / config.TRIPS_PER_DRIVER_HOUR).astype(int)
    out["drivers_needed_upper_80"] = np.ceil(out.upper_80 / config.TRIPS_PER_DRIVER_HOUR).astype(int)
    iv_path = config.SUBMISSION / f"team_{config.TEAM_NAME}_prediction_intervals.csv"
    out.to_csv(iv_path, index=False)
    write_report(cov, q, out, last)
    print(cov.to_string(index=False))
    print(f"wrote {iv_path.relative_to(config.ROOT)}")
    return sub, out, cov


def write_report(cov, q, out, last):
    by_zone = (out.groupby("zone").agg(mean_forecast=("predicted_trips", "mean"), peak_forecast=("predicted_trips", "max"),
                                       mean_width_80=("upper_80", "mean"))
               .assign(mean_width_80=lambda d: d.mean_width_80 - out.groupby("zone")["lower_80"].mean())
               .sort_values("mean_forecast", ascending=False).round(1).reset_index())
    c80 = cov.set_index("interval").loc["80%"]
    c90 = cov.set_index("interval").loc["90%"]
    lines = [
        f"# Stretch goal: prediction intervals (team {config.TEAM_NAME})",
        "",
        "Generated by `src/predict.py`. Files: `submission/team_" + config.TEAM_NAME + "_submission.csv` (the graded file: "
        "row_id, predicted_trips) and `submission/team_" + config.TEAM_NAME + "_prediction_intervals.csv` (the same forecast "
        "with 80% and 90% ranges and drivers needed).",
        "",
        "## Method",
        "",
        "Split-conformal intervals on scaled residuals. For each of the two latest 14-day folds, the final model "
        "settings are trained on everything before the fold and the errors are divided by sqrt(forecast + 1), because "
        "count errors grow with the size of the forecast. The 5/10/90/95% quantiles of these scaled errors give the "
        "range: forecast + quantile x sqrt(forecast + 1), floored at 0.",
        "",
        "## Does it hold? (honest check)",
        "",
        "Quantiles taken from the 4-17 Oct fold only, coverage measured on 18-31 Oct (data the quantiles never saw):",
        "",
        cov.to_markdown(index=False, floatfmt=".3f"),
        "",
        f"The 80% range caught {100 * c80.coverage_18_31_oct:.0f}% of actual hours and the 90% range "
        f"{100 * c90.coverage_18_31_oct:.0f}%, so the ranges are close to their stated level. The final ranges pool "
        f"both folds: 80% = forecast {q['80'][0]:+.2f} / {q['80'][1]:+.2f} x sqrt(forecast + 1); 90% = "
        f"{q['90'][0]:+.2f} / {q['90'][1]:+.2f} x sqrt(forecast + 1). The upper side is wider than the lower side: "
        "surges (holiday eves, big events) are under-forecast more often than quiet hours are over-forecast (D7).",
        "",
        "## Forecast by zone, 1-14 Nov 2025",
        "",
        by_zone.to_markdown(index=False, floatfmt=".1f"),
        "",
        "## How operations should use it",
        "",
        f"- Plan drivers from the forecast (`drivers_needed` = forecast / {config.TRIPS_PER_DRIVER_HOUR}, rounded up).",
        "- For hours where running short is costly (evening peak, event windows, holiday eves) staff to "
        "`drivers_needed_upper_80`: demand should exceed that only about 1 hour in 10.",
        "- The ranges assume the next fortnight behaves like October. A holiday eve or an event that is not in the "
        "calendar can still break them (D7).",
        "",
    ]
    (config.REPORTS / "D_stretch_uncertainty.md").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
